---
title: "Untitled"
author: "Yingjie"
date: "8/27/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---


# Setup
```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### To clear your environment 
remove(list = ls())

### data path
source('./Code/_path of data.R')
source('./Code/_package list.R')

library(dplyr)
library(ggplot2)
library(cowplot)

today <- format(Sys.time(), "%Y%m%d"); today
```




```{r}
### plot settings
unit_ns    <- 'cm'
width_1col <- 8.8   ## 1-column
width_2col <- 18    ## 2-column
font       <- 'sans'     ## "TT Arial"
font_size  <- 8          ##  Nature Sustainability: max = 7; min = 5
theme_ns <- 
  theme_bw()+
  theme(
    panel.grid.minor = element_blank(),
    legend.background = element_rect(fill="transparent"),
    legend.key.height = unit(0.15,"cm"),
    legend.key.width  = unit(0.15,"cm"),
    text = element_text(size=font_size + 2)
        )
```


# Data input


## SI data

```{r - income group}

load('./Data/Ancillary_Data_ISO3code_shp.RData') ## iso_eora, pop, gdp, shp, grp

grp_id <- grp %>%
  dplyr::mutate(group_id = as.numeric(gsub("\\D", "", inc_group))) %>% 
  dplyr::select(iso_a3, group_id) %>%
  dplyr::filter(!is.na(iso_a3)) %>%
  as.data.frame()

# 1: high 
# 2: mid-upper
# 3: mid-low
# 4: low
```



## CEPII distance data
  
  https://pacha.dev/cepiigeodist/reference/dist_cepii.html
  
```{r}
library(cepiigeodist)
### filter countries that share borders
# dist_cepii[dist_cepii$contig == 1, ]


dist_cepii <- dist_cepii %>%
  dplyr::mutate(iso_o = ifelse(iso_o == 'ZAR', 'COD', iso_o), iso_d = ifelse(iso_d == 'ZAR', 'COD', iso_d))

geo_cepii  <- geo_cepii


### corrections to the `geo` data ------------------------------------------------------------------
s <- 'Congo'          ## --> code change
s <- 'Romania'        ## --> code change
s <- 'Serbia'         ## --> code change
s <- 'Monaco'         ## not included in this data, use 'CHE' as a proxy (nearby and similar size)
s <- 'Liechtenstein'  ## not included in this data, use 'CHE' as a proxy (nearby and similar size)
s <- 'Cura'           ## --> to add
s <- 'Montenegro'     ## --> to add
s <- 'Sudan'          ## --> to add 'South Sudan', gained independence from the Republic of the Sudan in 2011
s <- 'Gaza'
s <- 'Palestine'      ## --> code change
geo_cepii %>%
  dplyr::filter(str_detect(pattern = s, country))


geo_cuw <- geo_cepii %>% 
  dplyr::filter(iso3== 'ANT') %>% 
  head(1) %>%
  dplyr::mutate(iso2 = ifelse(iso2 == 'AN', 'CU', iso2), 
                iso3 = ifelse(iso3 == 'ANT', 'CUW', iso3))

dist_cuw <- dist_cepii %>% 
  dplyr::filter(iso_o == 'ANT'| iso_d == 'ANT') %>% 
  dplyr::mutate(iso_o = ifelse(iso_o == 'ANT', 'CUW', iso_o), iso_d = ifelse(iso_d == 'ANT', 'CUW', iso_d)) %>%
  as.data.frame()

geo_mne <- geo_cepii %>% 
  dplyr::filter(iso3== 'YUG') %>% 
  head(1) %>%
  dplyr::mutate(iso2 = ifelse(iso2 == 'YU', 'ME', iso2), 
                iso3 = ifelse(iso3 == 'YUG', 'MNE', iso3))
dist_mne <- dist_cepii %>% 
  dplyr::filter(iso_o == 'YUG'| iso_d == 'YUG') %>% 
  dplyr::mutate(iso_o = ifelse(iso_o == 'YUG', 'MNE', iso_o), iso_d = ifelse(iso_d == 'YUG', 'MNE', iso_d)) %>%
  as.data.frame()

geo_ssd <- geo_cepii %>% 
  dplyr::filter(iso3== 'SDN') %>% 
  head(1) %>%
  dplyr::mutate(iso2 = ifelse(iso2 == 'SD', 'SS', iso2), iso3 = ifelse(iso3 == 'SDN', 'SSD', iso3))
dist_ssd <- dist_cepii %>% 
  dplyr::filter(iso_o == 'SDN'| iso_d == 'SDN') %>% 
  dplyr::mutate(iso_o = ifelse(iso_o == 'SDN', 'SSD', iso_o), iso_d = ifelse(iso_d == 'SDN', 'SSD', iso_d)) %>%
  as.data.frame()

geo_sun <- geo_cepii %>% 
  dplyr::filter(iso3== 'RUS') %>% 
  head(1) %>%
  dplyr::mutate(iso2 = ifelse(iso2 == 'RU', 'SU', iso2), iso3 = ifelse(iso3 == 'RUS', 'SUN', iso3))
dist_sun <- dist_cepii %>% 
  dplyr::filter(iso_o == 'RUS'| iso_d == 'RUS') %>% 
  dplyr::mutate(iso_o = ifelse(iso_o == 'RUS', 'SUN', iso_o), iso_d = ifelse(iso_d == 'RUS', 'SUN', iso_d)) %>%
  as.data.frame()


geo_lie <- geo_cepii %>% 
  dplyr::filter(iso3== 'CHE') %>% 
  head(1) %>%
  dplyr::mutate(iso2 = ifelse(iso2 == 'CH', 'LI', iso2), iso3 = ifelse(iso3 == 'CHE', 'LIE', iso3))
dist_lie <- dist_cepii %>% 
  dplyr::filter(iso_o == 'CHE'| iso_d == 'CHE') %>% 
  dplyr::mutate(iso_o = ifelse(iso_o == 'CHE', 'LIE', iso_o), iso_d = ifelse(iso_d == 'CHE', 'LIE', iso_d)) %>%
  as.data.frame()


geo_mco <- geo_cepii %>% 
  dplyr::filter(iso3== 'CHE') %>% 
  head(1) %>%
  dplyr::mutate(iso2 = ifelse(iso2 == 'CH', 'MC', iso2), iso3 = ifelse(iso3 == 'CHE', 'MCO', iso3))
dist_mco <- dist_cepii %>% 
  dplyr::filter(iso_o == 'CHE'| iso_d == 'CHE') %>% 
  dplyr::mutate(iso_o = ifelse(iso_o == 'CHE', 'MCO', iso_o), iso_d = ifelse(iso_d == 'CHE', 'MCO', iso_d)) %>%
  as.data.frame()



### ---
geo  <- geo_cepii %>%
  dplyr::mutate(iso3 = ifelse(iso3 == 'ZAR', 'COD', iso3), iso2 = ifelse(iso2 == 'ZR', 'CD', iso2)) %>%
  dplyr::mutate(iso3 = ifelse(iso3 == 'ROM', 'ROU', iso3)) %>%
  dplyr::mutate(iso3 = ifelse(iso3 == 'YUG', 'SRB', iso3), iso2 = ifelse(iso2 == 'YU', 'RS', iso2)) %>%
  dplyr::mutate(iso3 = ifelse(iso3 == 'PAL', 'PSE', iso3)) %>%
  rbind(., geo_cuw, geo_mne, geo_ssd, geo_sun, geo_lie, geo_mco)



### corrections to the `dist` data -----------------------------------------------------------------

dist <- dist_cepii %>%
  dplyr::mutate(iso_o = ifelse(iso_o == 'ZAR', 'COD', iso_o), iso_d = ifelse(iso_d == 'ZAR', 'COD', iso_d)) %>%
  dplyr::mutate(iso_o = ifelse(iso_o == 'ROM', 'ROU', iso_o), iso_d = ifelse(iso_d == 'ROM', 'ROU', iso_d)) %>%
  dplyr::mutate(iso_o = ifelse(iso_o == 'YUG', 'SRB', iso_o), iso_d = ifelse(iso_d == 'YUG', 'SRB', iso_d)) %>%
  dplyr::mutate(iso_o = ifelse(iso_o == 'PAL', 'PSE', iso_o), iso_d = ifelse(iso_d == 'PAL', 'PSE', iso_d)) %>%
  rbind(., dist_cuw, dist_mne, dist_ssd, dist_sun, dist_lie, dist_mco)



head(dist)

d <- dist$dist %>% as.numeric()

ctr_list_cepii <- dist %>%
  dplyr::select(1:2) %>%
  gather(key = 'od', value = 'iso', 1:2) %>%
  distinct(iso, .keep_all = T) %>%
  arrange(iso)

```



## Footprint data
```{r include=FALSE}

## load ft indicator list and direction data ----------------------
f <- paste0(dirname(dir.eora_cleaned), '/', 'direction_fts.rds'); f
direction_fts <- readRDS(file = f)

f <- paste0(dirname(dir.eora_cleaned), '/', 'direction.RData')
load(f) ## `direction`, `direction_clean`

### loop the normalization based on `direction` ------------------------------------------
ft_ind <- direction_clean %>%
  dplyr::select(ind, SDG_class, ShortName, direction, everything()) %>%
  dplyr::filter(!is.na(direction)) %>%
  dplyr::filter(Used == '1') %>%
  arrange(SDG_class)

cat(length(unique(ft_ind$ind)), 'indicators were included in the analysis.\n')


### !!! ** Choose how many type of flows will be used**
class_detail <- F
# class_detail <- T

###' class-detailed | class-aggregated 
###' ---------------------------------- #
###' high on low    | Vertical
###' high on high   | Vertical
###' low on high    | Horizontal
###' low on low     | Horizontal
###' -----------------------------------#


### --> pick an ft indicator as a test -----
# ind <- 'Water'
# ind <- 'student_flow'
# ind <- 'Landuse_forest'
# ind <- 'osh_fatal'


links_dist_type_collection <- data.frame()

for (ind in unique(ft_ind$ind)) {
  print(ind)
  
  xls <- paste0(dir.eora_cleaned, ind, '.xlsx'); xls
  
  ## if the data are from SHDB, we use 2019 to represent 2015
  is_shdb <- str_detect(string = ind, pattern = "SHDB")
  
  if (is_shdb == F) {
    mat <- readxl::read_excel(xls) %>% 
      ungroup() %>%
      dplyr::filter(year == 2015) 
  } else {
    mat <- readxl::read_excel(xls) %>% 
      ungroup() %>%
      dplyr::mutate(year = ifelse(year == 2019, 2015, year)) %>%
      dplyr::filter(year == 2015) 
  }
  
  ## to check if all the data have been loaded in 
  if (nrow(mat) < 1) {
    cat('\n\t This indicator has misisng data, pls check! \n')
  }
  
  links <- mat %>%
    gather(key = 'to', value = 'weight', 4:ncol(.)) %>%
    dplyr::rename('from' = 'iso3') %>%
    dplyr::mutate(type = ind) %>%
    dplyr::select(-ctr, -year) %>%
    arrange(from, to) %>%
    dplyr::distinct(from, to, .keep_all = T) %>%  
    as.data.frame()
  
  links_dist <- merge(x = links, y = dist, by.x = c('from', 'to'), by.y = c('iso_o', 'iso_d'), all.x = T) %>%
    merge(x = ., y = grp_id, by.x = 'from', by.y = 'iso_a3', all.x = T) %>%
    merge(x = ., y = grp_id, by.x = 'to',   by.y = 'iso_a3', all.x = T) %>%
    dplyr::mutate(
      group_od = paste0(group_id.x, group_id.y), ## group_od = 14, means o-1 sending; d-4 receiving 
      group_od = as.numeric(group_od)
      ) %>%
    dplyr::select(-group_id.x, -group_id.y) %>%
    arrange(to, from)
  
  
  ### --> check data 
  # links_dist_na <- links_dist %>% dplyr::filter(is.na(dist))
  # 
  # ctr_match_check <- mat %>%
  #   dplyr::select(2:3) %>%
  #   distinct(iso3, .keep_all = T) %>%
  #   merge(., ctr_list_cepii, by.x = 'iso3', by.y = 'iso', all.x = T) %>%
  #   arrange(!is.na(od))
  
  ### --> if we want to see a detailed classification of one group's impact on the other
  links_dist_detail <- links_dist %>%
    dplyr::mutate(
      od_direction = case_when(
      group_od %in% c(14, 13, 12) ~ 'low on high', ## 'vertical flow'
      group_od %in% c(41, 31, 21) ~ 'hign on low', ## 'horizontal flow'
      TRUE ~ 'other') 
    ) %>% as.data.frame()
    
  
  ### --> if we want to only see if the interaction happen across large income difference groups
  links_dist_aggr <- links_dist %>%
    dplyr::mutate(
      od_direction = case_when(
      group_od %in% c(14, 13, 12) ~ 'Vertical flows', ## 
      group_od %in% c(41, 31, 21) ~ 'Vertical flows', ## 
      TRUE ~ 'Horizontal flows') 
    ) %>% as.data.frame()
  
  
  
  ### !!! choose one for analysis
  if (class_detail == F) {
    links_dist_type <- links_dist_aggr
  } else if (class_detail == T) {
    links_dist_type <- links_dist_detail
  } else {
    print('NA ...................')
    break
  }
  
  
  links_dist_type_collection <- rbind(links_dist_type_collection, links_dist_type)
  
}

cat(length(unique(links_dist_type_collection$type)), 'indicators were included in the analysis.\n')
```




# Analysis - FT distance 

  For country *m*, on average, how far has its impact reached to? 
  
  Here we use the *footprint distance* to measure the *impact distance*.
  
## distance measure  
```{r}

## for a receiving country, calculate its impact distance --------------------------------- 
ft_d <- links_dist_type_collection %>%
  dplyr::mutate(ftd = weight * dist) %>%                  ## flow * distance
  dplyr::group_by(to, type, od_direction) %>%
  dplyr::summarise(dq_sum = sum(ftd, na.rm = T),          ## total (flow * distance)
                   q_sum  = sum(weight, na.rm = T)) %>%   ## total flow
  as.data.frame() %>%
  dplyr::mutate(d_avg_ft = dq_sum/q_sum/1000) %>%         ## average distance of each unit of flows
  merge(x = ., 
        y = ft_ind %>% dplyr::select(-direction), 
        by.x = 'type', by.y = 'ind', all.x = T)


links_dist_type_collection %>% 
  dplyr::group_by(type, od_direction) %>%
  tally()



od_direction_levels <- unique(links_dist_type_collection$od_direction); od_direction_levels
od_direction_count  <- length(od_direction_levels); od_direction_count
if (od_direction_count <= 2) {
  od_direction_levels <-  rev(od_direction_levels)
} else {
  od_direction_levels <-  c("hign on low", "low on high", "other")
}
od_direction_labels <- str_to_sentence(od_direction_levels)


## 1. mean distance between countries 
hist(dist_cepii$dist)
mean(dist_cepii$dist, na.rm=T) ## --> 8481.7 km

## 2. mean impact distance between countries 
hist(ft_d$d_avg_ft)
mean(ft_d$d_avg_ft, na.rm=T)       ## --> 5780.7 km
d_max <- max(ft_d$d_avg_ft, na.rm=T) %>% round(., digits = 1); d_max


firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

ft_ind_ls <- unique(ft_ind$ind); ft_ind_ls
ft_ind_ls_levels <- ft_ind_ls
ft_ind_ls_labels <- ft_ind_ls_levels %>% 
  gsub('_|TradeMatrix|Annual crops|irri', ' ', x = .) %>%
  gsub('Osh', 'OSH ', x = .) %>%
  gsub('Energy', 'Energy ', x = .) %>%
  gsub('Landuse', 'Landuse ', x = .) %>%
  gsub('Nitrogen', 'Nitrogen ', x = .) %>%
  gsub('Phosphorus', 'Phosphorus ', x = .) %>%
  trimws(.) %>%
  firstup(.)
```




```{r plot - by ft indicator - ex6}
p1 <- ft_d %>% 
  # dplyr::filter(SDG_class != 'Soci') %>% ## subset for easy plot
  dplyr::mutate(od_direction = factor(x = od_direction, levels = od_direction_levels, labels = od_direction_labels)) %>%
  
  ### - used this before 2023-07-01
  # dplyr::mutate(type = factor(x = type, levels = ft_ind_ls_levels, labels = ft_ind_ls_labels)) %>%
  ### - change on since  2023-07-17
  dplyr::mutate(type = ShortName) %>%
  arrange(type) %>%
  dplyr::mutate(type = as.factor(type)) %>%
  
  ### - plot
  ggplot() +
  geom_histogram(aes(x = d_avg_ft, fill = od_direction), position="identity", alpha=0.5, show.legend = T) +
  geom_vline(aes(xintercept=mean(d_avg_ft, na.rm=T)), color="red", linewidth = .5) + # linetype="dashed", alpha = .5, 
  # ggplot2::annotate(
  #   "text", 
  #   x = round(mean(ft_d$d_avg_ft, na.rm=T)*1, digits = 1),
  #   y = 2, 
  #   label = round(mean(ft_d$d_avg_ft, na.rm=T), digits = 1), 
  #   colour = "red", size = 2) +
  # facet_wrap(~od_direction, ncol = 1) + ## for one indicator
  # facet_grid(type~od_direction) +
  facet_wrap(~type, ncol = 4) +
  theme_ns +
  # theme_minimal() +
  theme(
    # axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = c(0.99, 0.01),
    legend.justification = c(1, 0), # right bottom justification
    legend.box.margin = margin(r = 0, b = 0, unit = "mm"), # small margin
    axis.title.y = element_blank(), 
    panel.grid = element_blank(),
    ) +
  ylim(0,20) + 
  scale_x_continuous(
    limits = c(0, ceiling(d_max+0.01)), 
    breaks = c(seq(0, d_max, 9), round(mean(ft_d$d_avg_ft, na.rm=T), digits = 1))) +
  xlab(label = bquote('Distance (10'^3~'km)')) + 
  labs(fill='') # Impact pairs


ggarrange(p1, labels = '')
fname <- paste0(dir.fig, '01main/', 'ex_6_ImpactDistance_byFT',
                '_class', od_direction_count, '_', today, '.jpg'); fname
ggsave(filename = fname, plot = last_plot(), width = 7, height = 7, units = 'in', dpi = 300)
```






```{r plot - summary across indicators - 2d}
ind <- 'AvgAcrossFT'
ft_d_summary <- ft_d %>%
  Rmisc::summarySE(measurevar= "d_avg_ft", groupvars = c('to', 'od_direction'), na.rm = T) %>%
  as.data.frame()
  
d_max_ <- max(ft_d_summary$d_avg_ft, na.rm=T) %>% ceiling(.); d_max_

p <- ft_d_summary %>% 
  # dplyr::filter(SDG_class != 'Soci') %>% ## subset for easy plot
  dplyr::mutate(od_direction = factor(x = od_direction, levels = od_direction_levels, labels = od_direction_labels)) %>%
  ggplot() +
  geom_histogram(aes(x = d_avg_ft, fill = od_direction), position="identity", alpha=0.5, show.legend = F) +
  geom_vline(aes(xintercept=mean(d_avg_ft, na.rm=T)), color="red", size = .5) + # linetype="dashed", alpha = .5, 
  facet_wrap(~od_direction, ncol = 1) + ## for one indicator
  theme_ns +
  # theme_minimal() +
  theme(
    # axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_blank(), 
    panel.grid = element_blank(),
    ) +
  ylim(0,20) + 
  scale_x_continuous(
    limits = c(0, d_max_), 
    breaks = c(seq(0, d_max_, 9), round(mean(ft_d$d_avg_ft, na.rm=T), digits = 1))) +
  xlab(label = bquote('Distance (10'^3~'km)')) + 
  labs(fill='Impact pair')
ggarrange(p, labels = 'd')
fname <- paste0(dir.fig, '01main/', 'fig2d_ImpactDistance_', ind,
                od_direction_count, 'grp_', today, '.jpg'); fname
ggsave(filename = fname, plot = last_plot(), width = 7.5/2, height = 7.5/2, units = 'in', dpi = 300)
```



## count % of nearby (contiguous) or not
```{r}

## impact distance by group of 'nearby or not'
ft_FarNear <- links_dist_type_collection %>%
  dplyr::group_by(contig) %>%
  dplyr::summarise(q_sum  = sum(weight, na.rm = T)) %>%
  as.data.frame() %>%
  dplyr::mutate(
    sum = sum(links_dist_type_collection$weight, na.rm = T),
    pct = q_sum/sum
    ) %>%
  as.data.frame()


## number of countries that are nearby
ft_FarNear_n <- links_dist_type_collection %>%
  dplyr::group_by(contig) %>%
  dplyr::summarise(n = n()) %>%
  as.data.frame() %>%
  dplyr::mutate(
    sum = sum(n, na.rm = T),
    pct = n/sum
    ) %>%
  as.data.frame()
```

